// Datos iniciales del plan de cuentas (VEN-NIF adaptado a un centro de salud) y de los
// centros de costo de CECIAMB. Va como migración para que el bot de despliegue lo cargue
// también en producción; si ya hay cuentas no toca nada.

/** @param {import('knex').Knex} knex */
export async function up(knex) {
  // Centros de costo base
  const centrosCosto = [
    { codigo: 'ADM', nombre: 'Administración y Finanzas' },
    { codigo: 'EME', nombre: 'Emergencia y Triaje' },
    { codigo: 'QUI', nombre: 'Quirófano y Cirugía' },
    { codigo: 'HOS', nombre: 'Hospitalización' },
    { codigo: 'FAR', nombre: 'Farmacia Hospitalaria' },
    { codigo: 'LAB', nombre: 'Laboratorio Clínico' },
    { codigo: 'IMG', nombre: 'Imagenología y Rayos X' },
    { codigo: 'UCI', nombre: 'Unidad de Cuidados Intensivos' },
  ]

  for (const cc of centrosCosto) {
    await knex('centros_costo')
      .insert({ ...cc, activo: true })
      .onConflict('codigo')
      .ignore()
  }

  // Si ya existen cuentas cargadas, no duplicar
  const totalCuentas = await knex('cuentas').count({ total: '*' }).first()
  if (Number(totalCuentas?.total ?? 0) > 0) return

  // Catálogo jerárquico base
  const cuentas = [
    // --- 1. ACTIVO ---
    {
      codigo: '1',
      nombre: 'ACTIVO',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 1,
      es_movimiento: false,
      padre: null,
    },
    {
      codigo: '1.1',
      nombre: 'ACTIVO CORRIENTE',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 2,
      es_movimiento: false,
      padre: '1',
    },
    {
      codigo: '1.1.01',
      nombre: 'Efectivo y Equivalentes de Efectivo',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 3,
      es_movimiento: false,
      padre: '1.1',
    },
    {
      codigo: '1.1.01.01',
      nombre: 'Caja',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 4,
      es_movimiento: false,
      padre: '1.1.01',
    },
    {
      codigo: '1.1.01.01.001',
      nombre: 'Caja Principal',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 5,
      es_movimiento: true,
      padre: '1.1.01.01',
    },
    {
      codigo: '1.1.01.01.002',
      nombre: 'Caja Chica Emergencia',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 5,
      es_movimiento: true,
      padre: '1.1.01.01',
    },
    {
      codigo: '1.1.01.02',
      nombre: 'Bancos Nacionales',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 4,
      es_movimiento: false,
      padre: '1.1.01',
    },
    {
      codigo: '1.1.01.02.001',
      nombre: 'Banco Mercantil Cta. Cte.',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 5,
      es_movimiento: true,
      padre: '1.1.01.02',
    },
    {
      codigo: '1.1.01.02.002',
      nombre: 'Banesco Cta. Cte.',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 5,
      es_movimiento: true,
      padre: '1.1.01.02',
    },
    {
      codigo: '1.1.01.02.003',
      nombre: 'Banco de Venezuela Cta. Cte.',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 5,
      es_movimiento: true,
      padre: '1.1.01.02',
    },

    {
      codigo: '1.1.02',
      nombre: 'Cuentas por Cobrar Comerciales',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 3,
      es_movimiento: false,
      padre: '1.1',
    },
    {
      codigo: '1.1.02.01',
      nombre: 'Pacientes Particulares',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 4,
      es_movimiento: true,
      padre: '1.1.02',
    },
    {
      codigo: '1.1.02.02',
      nombre: 'Empresas y Aseguradoras',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 4,
      es_movimiento: true,
      padre: '1.1.02',
    },

    {
      codigo: '1.1.03',
      nombre: 'Inventarios',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 3,
      es_movimiento: false,
      padre: '1.1',
    },
    {
      codigo: '1.1.03.01',
      nombre: 'Inventario Medicamentos Farmacia',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 4,
      es_movimiento: true,
      padre: '1.1.03',
    },
    {
      codigo: '1.1.03.02',
      nombre: 'Inventario Material Médico Quirúrgico',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 4,
      es_movimiento: true,
      padre: '1.1.03',
    },

    {
      codigo: '1.2',
      nombre: 'ACTIVO NO CORRIENTE',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 2,
      es_movimiento: false,
      padre: '1',
    },
    {
      codigo: '1.2.01',
      nombre: 'Propiedad, Planta y Equipos',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 3,
      es_movimiento: false,
      padre: '1.2',
    },
    {
      codigo: '1.2.01.01',
      nombre: 'Equipos Médicos y Quirúrgicos',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 4,
      es_movimiento: true,
      padre: '1.2.01',
    },
    {
      codigo: '1.2.01.02',
      nombre: 'Equipos de Computación y Sistemas',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 4,
      es_movimiento: true,
      padre: '1.2.01',
    },
    {
      codigo: '1.2.01.03',
      nombre: 'Mobiliario Clínico y de Oficina',
      tipo: 'ACTIVO',
      naturaleza: 'DEUDORA',
      nivel: 4,
      es_movimiento: true,
      padre: '1.2.01',
    },
    {
      codigo: '1.2.01.04',
      nombre: 'Depreciación Acumulada Equipos Médicos',
      tipo: 'ACTIVO',
      naturaleza: 'ACREEDORA',
      nivel: 4,
      es_movimiento: true,
      padre: '1.2.01',
    },

    // --- 2. PASIVO ---
    {
      codigo: '2',
      nombre: 'PASIVO',
      tipo: 'PASIVO',
      naturaleza: 'ACREEDORA',
      nivel: 1,
      es_movimiento: false,
      padre: null,
    },
    {
      codigo: '2.1',
      nombre: 'PASIVO CORRIENTE',
      tipo: 'PASIVO',
      naturaleza: 'ACREEDORA',
      nivel: 2,
      es_movimiento: false,
      padre: '2',
    },
    {
      codigo: '2.1.01',
      nombre: 'Cuentas por Pagar Comerciales',
      tipo: 'PASIVO',
      naturaleza: 'ACREEDORA',
      nivel: 3,
      es_movimiento: false,
      padre: '2.1',
    },
    {
      codigo: '2.1.01.01',
      nombre: 'Proveedores de Medicamentos e Insumos',
      tipo: 'PASIVO',
      naturaleza: 'ACREEDORA',
      nivel: 4,
      es_movimiento: true,
      padre: '2.1.01',
    },
    {
      codigo: '2.1.01.02',
      nombre: 'Honorarios Médicos por Pagar',
      tipo: 'PASIVO',
      naturaleza: 'ACREEDORA',
      nivel: 4,
      es_movimiento: true,
      padre: '2.1.01',
    },

    {
      codigo: '2.1.02',
      nombre: 'Retenciones y Obligaciones Tributarias',
      tipo: 'PASIVO',
      naturaleza: 'ACREEDORA',
      nivel: 3,
      es_movimiento: false,
      padre: '2.1',
    },
    {
      codigo: '2.1.02.01',
      nombre: 'Retención ISLR Proveedores',
      tipo: 'PASIVO',
      naturaleza: 'ACREEDORA',
      nivel: 4,
      es_movimiento: true,
      padre: '2.1.02',
    },
    {
      codigo: '2.1.02.02',
      nombre: 'Retención IVA por Enterar',
      tipo: 'PASIVO',
      naturaleza: 'ACREEDORA',
      nivel: 4,
      es_movimiento: true,
      padre: '2.1.02',
    },

    {
      codigo: '2.1.03',
      nombre: 'Obligaciones Laborales',
      tipo: 'PASIVO',
      naturaleza: 'ACREEDORA',
      nivel: 3,
      es_movimiento: false,
      padre: '2.1',
    },
    {
      codigo: '2.1.03.01',
      nombre: 'Sueldos y Salarios por Pagar',
      tipo: 'PASIVO',
      naturaleza: 'ACREEDORA',
      nivel: 4,
      es_movimiento: true,
      padre: '2.1.03',
    },
    {
      codigo: '2.1.03.02',
      nombre: 'Prestaciones Sociales por Pagar',
      tipo: 'PASIVO',
      naturaleza: 'ACREEDORA',
      nivel: 4,
      es_movimiento: true,
      padre: '2.1.03',
    },

    // --- 3. PATRIMONIO ---
    {
      codigo: '3',
      nombre: 'PATRIMONIO',
      tipo: 'PATRIMONIO',
      naturaleza: 'ACREEDORA',
      nivel: 1,
      es_movimiento: false,
      padre: null,
    },
    {
      codigo: '3.1',
      nombre: 'Capital Social',
      tipo: 'PATRIMONIO',
      naturaleza: 'ACREEDORA',
      nivel: 2,
      es_movimiento: false,
      padre: '3',
    },
    {
      codigo: '3.1.01',
      nombre: 'Capital Suscrito y Pagado',
      tipo: 'PATRIMONIO',
      naturaleza: 'ACREEDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '3.1',
    },
    {
      codigo: '3.2',
      nombre: 'Resultados Acumulados',
      tipo: 'PATRIMONIO',
      naturaleza: 'ACREEDORA',
      nivel: 2,
      es_movimiento: false,
      padre: '3',
    },
    {
      codigo: '3.2.01',
      nombre: 'Ganancias o Pérdidas Acumuladas',
      tipo: 'PATRIMONIO',
      naturaleza: 'ACREEDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '3.2',
    },
    {
      codigo: '3.2.02',
      nombre: 'Resultado del Ejercicio Actual',
      tipo: 'PATRIMONIO',
      naturaleza: 'ACREEDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '3.2',
    },

    // --- 4. INGRESOS ---
    {
      codigo: '4',
      nombre: 'INGRESOS',
      tipo: 'INGRESO',
      naturaleza: 'ACREEDORA',
      nivel: 1,
      es_movimiento: false,
      padre: null,
    },
    {
      codigo: '4.1',
      nombre: 'Ingresos Operacionales Hospitalarios',
      tipo: 'INGRESO',
      naturaleza: 'ACREEDORA',
      nivel: 2,
      es_movimiento: false,
      padre: '4',
    },
    {
      codigo: '4.1.01',
      nombre: 'Servicios de Hospitalización',
      tipo: 'INGRESO',
      naturaleza: 'ACREEDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '4.1',
    },
    {
      codigo: '4.1.02',
      nombre: 'Servicios de Quirófano y Cirugía',
      tipo: 'INGRESO',
      naturaleza: 'ACREEDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '4.1',
    },
    {
      codigo: '4.1.03',
      nombre: 'Servicios de Emergencia y Triaje',
      tipo: 'INGRESO',
      naturaleza: 'ACREEDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '4.1',
    },
    {
      codigo: '4.1.04',
      nombre: 'Servicios de Laboratorio Clínico',
      tipo: 'INGRESO',
      naturaleza: 'ACREEDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '4.1',
    },
    {
      codigo: '4.1.05',
      nombre: 'Venta de Medicamentos e Insumos Farmacia',
      tipo: 'INGRESO',
      naturaleza: 'ACREEDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '4.1',
    },

    // --- 5. COSTOS ---
    {
      codigo: '5',
      nombre: 'COSTOS',
      tipo: 'COSTO',
      naturaleza: 'DEUDORA',
      nivel: 1,
      es_movimiento: false,
      padre: null,
    },
    {
      codigo: '5.1',
      nombre: 'Costos de Servicios de Salud',
      tipo: 'COSTO',
      naturaleza: 'DEUDORA',
      nivel: 2,
      es_movimiento: false,
      padre: '5',
    },
    {
      codigo: '5.1.01',
      nombre: 'Costo de Medicamentos Dispensados',
      tipo: 'COSTO',
      naturaleza: 'DEUDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '5.1',
    },
    {
      codigo: '5.1.02',
      nombre: 'Costo de Material Médico Quirúrgico',
      tipo: 'COSTO',
      naturaleza: 'DEUDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '5.1',
    },
    {
      codigo: '5.1.03',
      nombre: 'Honorarios Médicos Especialistas Directos',
      tipo: 'COSTO',
      naturaleza: 'DEUDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '5.1',
    },
    {
      codigo: '5.1.04',
      nombre: 'Costo de Personal de Enfermería Asistencial',
      tipo: 'COSTO',
      naturaleza: 'DEUDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '5.1',
    },

    // --- 6. GASTOS ---
    {
      codigo: '6',
      nombre: 'GASTOS',
      tipo: 'GASTO',
      naturaleza: 'DEUDORA',
      nivel: 1,
      es_movimiento: false,
      padre: null,
    },
    {
      codigo: '6.1',
      nombre: 'Gastos de Administración y Operación',
      tipo: 'GASTO',
      naturaleza: 'DEUDORA',
      nivel: 2,
      es_movimiento: false,
      padre: '6',
    },
    {
      codigo: '6.1.01',
      nombre: 'Sueldos y Salarios Administrativos',
      tipo: 'GASTO',
      naturaleza: 'DEUDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '6.1',
    },
    {
      codigo: '6.1.02',
      nombre: 'Mantenimiento Preventivo de Equipos Médicos',
      tipo: 'GASTO',
      naturaleza: 'DEUDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '6.1',
    },
    {
      codigo: '6.1.03',
      nombre: 'Servicios Básicos (Electricidad, Agua, Redes)',
      tipo: 'GASTO',
      naturaleza: 'DEUDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '6.1',
    },
    {
      codigo: '6.1.04',
      nombre: 'Materiales y Artículos de Oficina',
      tipo: 'GASTO',
      naturaleza: 'DEUDORA',
      nivel: 3,
      es_movimiento: true,
      padre: '6.1',
    },
  ]

  // Insertar en orden respetando FKs (padres primero)
  const mapaIds = new Map()

  for (const c of cuentas) {
    const padreId = c.padre ? (mapaIds.get(c.padre) ?? null) : null
    const [id] = await knex('cuentas').insert({
      codigo: c.codigo,
      nombre: c.nombre,
      tipo: c.tipo,
      naturaleza: c.naturaleza,
      nivel: c.nivel,
      padre_id: padreId,
      es_movimiento: c.es_movimiento,
      activa: true,
    })
    mapaIds.set(c.codigo, id)
  }
}

/** Los datos se van con las tablas al revertir la migración anterior */
export async function down() {}
